### ISSUE TITLE
Add examples of creating custom SPARQL functions

### ISSUE THREAD

**Issue by arnikz** [NLeSC/ldm-sig#9] opened 2017-10-18 14:24 UTC
E.g. using Python's [RDFlib](https://github.com/RDFLib/rdflib/pull/723)

**Comment by romulogoncalves** [comment] 2018-01-26 09:54
The issue is open for too long and it was just about a tutorial, we will close it.
It belongs to the old SIG.

**Closed as completed by romulogoncalves** 2018-01-26 09:54 UTC
Labels: old SIG
